### ISSUE TITLE
Dependency grog.sudo

### ISSUE THREAD

**Issue by elchior** [GROG/ansible-role-management-user#10]
Hello,
The grog.management-user role still has a dependency to grog.sudo 1.4.4.
I think it should be updated to 1.6.

Another point. Sometimes capital letters are used and sometimes small letters. Is there a reason for that?

Kind regards,
Elchior

**Comment by groggemans** [comment]
Version with updated dependencies created and released.

The different casing is the result of a bad decision, I should have just gone for lower case.. I think 99% of the time lower case will work though.

Kind regards,
Gertjan
