### ISSUE TITLE
Default home directory

### ISSUE THREAD

**Issue by deadbeef2000** [GROG/ansible-role-management-user#11]
The default home directory location shouldn't be `/home` as a management user shouldn't be used by a person anyway. In my opinion, it should default to something more sane, like `/var/lib/management-users` or something alike.
I would like to use this role on my mail VM, but on this machine a NFS share is mounted to `/home` where the users mail are stored and their `.forward` files are accessed. For that reason, I'd like the default path of the home directory for management users to be somewhere else in the FHS.

**Comment by groggemans** [comment]
Hi @deadbeef2000 

This role doesn't make any assumptions about home dir locations. It's a pure meta role wrapping some other roles which also don't make any assumptions on these locations. The upstream roles use the ansible user module defaults, which I believe follow the system defaults. (`/home/<username>`)

If you do want to use the module with a different homedir location you can easily pass the `home` parameter for the specific user you are creating.

```yaml
management_user_settings:
  name: xyz
  home: /var/lib/management-users/xyz
```
