### ISSUE TITLE
remove authorized_key after user removal

### ISSUE THREAD

**Issue by danielmotaleite** [GROG/ansible-role-management-user#7]
I added the user state: absent, but without the remove: yes and then authorized_keys will fail with:

`Failed to lookup user backup-user: 'getpwnam(): name not found: backup-user'`

So that is, if there is no user already, the authorized_key will fail later on

i'm using ansible 2.8.0

**Comment by groggemans** [comment]
Hi Daniel

Thank you for using this role!

Looks like a bug in the authorized-keys sub-role. As that role is also managed by me you don't need to make an extra ticket over there.

I have a very busy week but will try to find some time to work on a fix.

**Comment by groggemans** [comment]
As of v1.2.8 this should be fixed.

Thank you for your report!

**Comment by danielmotaleite** [comment]
Thanks for the fix, but it is incomplete, we do not define the state when the user is present, only when it is absent, so:

`The conditional check 'item.0.state != "absent"' failed. The error was: error while evaluating conditional (item.0.state != "absent"): 'dict object' has no attribute 'state'`

The fix should be easy:
```
When: 'item.0.state is undefined or item.0.state != "absent"'
```

It works for me... but i suspect if someone changed the GROG.user default  `user_state: present` to absent, it may not work as expected 

Maybe this:
```
when: '(item.0.state is undefined and user_state != "absent" ) or ( item.0.state is defined and item.0.state != "absent" )'
```
But i'm not sure if the authorized_key can see the user_state

**Comment by groggemans** [comment]
Looks like I forgot a default value in the authorized-keys role. (I also fixed this issue for the sudo part, and there I did add a default to catch undefined state values)

I'll try to fix it today or tomorrow, thank you for the follow up!

**Comment by groggemans** [comment]
I decided to remove the option to set a default `user_state` from the user role. The original idea was to make it possible to force people in explicitly enabling users. But in the end I think it leads to counter intuitive and unclear code. Ansible users don't expect that a resource without a state defined is not created.

Fix is on the way.

**Comment by groggemans** [comment]
Let's hope I don't need a third time, v1.2.9 should do it!

Thank you!
