### ISSUE TITLE
Can't figure out how to deploy keys for more users

### ISSUE THREAD

**Issue by Tuimalila** [GROG/ansible-role-management-user#9]
First thank you for this ansible-management-user role. I know this is not a bug - I'm trying to make it work - but seem not to understand something. The role works, just keys don't get copied to servers _authorized_keys_ file, if I want to create more users, not just one. One user in defaults/main.yml works, if I list more, keys don't get copied.

**Comment by groggemans** [comment]
Hi @Tuimalila 

Sorry that I couldn't get back to you earlier, I had a busy week.

Have you been able to get it working?

Kind regards,
Gertjan
